# Generated by Django 5.1.3 on 2024-11-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SpyCat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("breed", models.CharField(max_length=100, verbose_name="breed")),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(verbose_name="years of experience"),
                ),
                (
                    "salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="salary"
                    ),
                ),
            ],
        ),
    ]
