# Generated by Django 5.1.3 on 2024-11-27 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spycats", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="is completed"),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="spycat",
            constraint=models.CheckConstraint(
                condition=models.Q(("salary__gt", 0)), name="salary_greater_than_zero"
            ),
        ),
        migrations.AddField(
            model_name="mission",
            name="cat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="spycats.spycat",
            ),
        ),
    ]
