services:
  spycats:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py runserver ${DJANGO_HOST}:${DJANGO_PORT}"
    volumes:
      - ./:/app
      - my_media:/files/media
    depends_on:
      - db
    networks:
      - spy


  db:
    image: postgres:16.0-alpine3.17
    restart: always
    env_file:
      - .env
    ports:
      - "${PG_PORT}:${PG_PORT}"
    volumes:
      - my_db:$PGDATA
    networks:
      - spy

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - spy
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 60s
      retries: 5
    restart: always

networks:
  spy:
    driver: bridge

volumes:
  my_db:
  my_media:
